// default package
// Generated 02/10/2017 18:37:43 by Hibernate Tools 5.2.3.Final
package tienda.dto;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
@SuppressWarnings("serial")
public class Estado implements java.io.Serializable {

	private String idestado;
	private Tabla tabla;
	private String nombreestado;
	private Date fechareg;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private Set<Rol> rols = new HashSet<Rol>(0);
	private boolean selected;

	public Estado() {
	}

	public Estado(String idestado, Tabla tabla, String nombreestado, Date fechareg) {
		this.idestado = idestado;
		this.tabla = tabla;
		this.nombreestado = nombreestado;
		this.fechareg = fechareg;
	}

	public Estado(String idestado, Tabla tabla, String nombreestado, Date fechareg, Set<Usuario> usuarios,
			Set<Rol> rols) {
		this.idestado = idestado;
		this.tabla = tabla;
		this.nombreestado = nombreestado;
		this.fechareg = fechareg;
		this.usuarios = usuarios;
		this.rols = rols;
	}

	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	public String getIdestado() {
		return this.idestado;
	}

	public void setIdestado(String idestado) {
		this.idestado = idestado;
	}

	public Tabla getTabla() {
		return this.tabla;
	}

	public void setTabla(Tabla tabla) {
		this.tabla = tabla;
	}

	public String getNombreestado() {
		return this.nombreestado;
	}

	public void setNombreestado(String nombreestado) {
		this.nombreestado = nombreestado;
	}

	public Date getFechareg() {
		return this.fechareg;
	}

	public void setFechareg(Date fechareg) {
		this.fechareg = fechareg;
	}

	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	public Set<Rol> getRols() {
		return this.rols;
	}

	public void setRols(Set<Rol> rols) {
		this.rols = rols;
	}

}
