// default package
// Generated 02/10/2017 18:37:43 by Hibernate Tools 5.2.3.Final
package tienda.dto;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facturacab generated by hbm2java
 */
@SuppressWarnings("serial")
public class Facturacab implements java.io.Serializable {

	private Integer idfacturacab;
	private Cliente cliente;
	private double total;
	private Date fechareg;
	private double descuento;
	private Set<Facturadet> facturadets = new HashSet<Facturadet>(0);

	public Facturacab() {
	}

	public Facturacab(Cliente cliente, double total, Date fechareg, double descuento) {
		this.cliente = cliente;
		this.total = total;
		this.fechareg = fechareg;
		this.descuento = descuento;
	}

	public Facturacab(Cliente cliente, double total, Date fechareg, double descuento, Set<Facturadet> facturadets) {
		this.cliente = cliente;
		this.total = total;
		this.fechareg = fechareg;
		this.descuento = descuento;
		this.facturadets = facturadets;
	}

	public Integer getIdfacturacab() {
		return this.idfacturacab;
	}

	public void setIdfacturacab(Integer idfacturacab) {
		this.idfacturacab = idfacturacab;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	public Date getFechareg() {
		return this.fechareg;
	}

	public void setFechareg(Date fechareg) {
		this.fechareg = fechareg;
	}

	public double getDescuento() {
		return this.descuento;
	}

	public void setDescuento(double descuento) {
		this.descuento = descuento;
	}

	public Set<Facturadet> getFacturadets() {
		return this.facturadets;
	}

	public void setFacturadets(Set<Facturadet> facturadets) {
		this.facturadets = facturadets;
	}

}
