// default package
// Generated 02/10/2017 18:37:43 by Hibernate Tools 5.2.3.Final
package tienda.dto;
import java.util.Date;

/**
 * Facturadet generated by hbm2java
 */
@SuppressWarnings("serial")
public class Facturadet implements java.io.Serializable {

	private Integer idfacturadet;
	private Facturacab facturacab;
	private Producto producto;
	private double precio;
	private int cantidad;
	private double subtotal;
	private Date fechareg;

	public Facturadet() {
	}

	public Facturadet(Facturacab facturacab, Producto producto, double precio, int cantidad, double subtotal,
			Date fechareg) {
		this.facturacab = facturacab;
		this.producto = producto;
		this.precio = precio;
		this.cantidad = cantidad;
		this.subtotal = subtotal;
		this.fechareg = fechareg;
	}

	public Integer getIdfacturadet() {
		return this.idfacturadet;
	}

	public void setIdfacturadet(Integer idfacturadet) {
		this.idfacturadet = idfacturadet;
	}

	public Facturacab getFacturacab() {
		return this.facturacab;
	}

	public void setFacturacab(Facturacab facturacab) {
		this.facturacab = facturacab;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public double getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(double subtotal) {
		this.subtotal = subtotal;
	}

	public Date getFechareg() {
		return this.fechareg;
	}

	public void setFechareg(Date fechareg) {
		this.fechareg = fechareg;
	}

}
