// default package
// Generated 02/10/2017 18:37:43 by Hibernate Tools 5.2.3.Final
package tienda.dto;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
@SuppressWarnings("serial")
public class Marca implements java.io.Serializable {

	private String idmarca;
	private String nombre;
	private Date fechareg;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Marca() {
	}

	public Marca(String idmarca, String nombre, Date fechareg) {
		this.idmarca = idmarca;
		this.nombre = nombre;
		this.fechareg = fechareg;
	}

	public Marca(String idmarca, String nombre, Date fechareg, Set<Producto> productos) {
		this.idmarca = idmarca;
		this.nombre = nombre;
		this.fechareg = fechareg;
		this.productos = productos;
	}

	public String getIdmarca() {
		return this.idmarca;
	}

	public void setIdmarca(String idmarca) {
		this.idmarca = idmarca;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechareg() {
		return this.fechareg;
	}

	public void setFechareg(Date fechareg) {
		this.fechareg = fechareg;
	}

	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
