// default package
// Generated 02/10/2017 18:37:43 by Hibernate Tools 5.2.3.Final
package tienda.dto;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
@SuppressWarnings("serial")
public class Producto implements java.io.Serializable {

	private String idproducto;
	private Marca marca;
	private Proveedor proveedor;
	private String nombre;
	private String codigobarra;
	private double precio;
	private int cantidad;
	private Date fechareg;
	private Set<Facturadet> facturadets = new HashSet<Facturadet>(0);

	public Producto() {
	}

	public Producto(String idproducto, Marca marca, Proveedor proveedor, String nombre, String codigobarra,
			double precio, int cantidad, Date fechareg) {
		this.idproducto = idproducto;
		this.marca = marca;
		this.proveedor = proveedor;
		this.nombre = nombre;
		this.codigobarra = codigobarra;
		this.precio = precio;
		this.cantidad = cantidad;
		this.fechareg = fechareg;
	}

	public Producto(String idproducto, Marca marca, Proveedor proveedor, String nombre, String codigobarra,
			double precio, int cantidad, Date fechareg, Set<Facturadet> facturadets) {
		this.idproducto = idproducto;
		this.marca = marca;
		this.proveedor = proveedor;
		this.nombre = nombre;
		this.codigobarra = codigobarra;
		this.precio = precio;
		this.cantidad = cantidad;
		this.fechareg = fechareg;
		this.facturadets = facturadets;
	}

	public String getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(String idproducto) {
		this.idproducto = idproducto;
	}

	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigobarra() {
		return this.codigobarra;
	}

	public void setCodigobarra(String codigobarra) {
		this.codigobarra = codigobarra;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public Date getFechareg() {
		return this.fechareg;
	}

	public void setFechareg(Date fechareg) {
		this.fechareg = fechareg;
	}

	public Set<Facturadet> getFacturadets() {
		return this.facturadets;
	}

	public void setFacturadets(Set<Facturadet> facturadets) {
		this.facturadets = facturadets;
	}

}
