// default package
// Generated 02/10/2017 18:37:43 by Hibernate Tools 5.2.3.Final
package tienda.dto;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
@SuppressWarnings("serial")
public class Rol implements java.io.Serializable {

	private String idrol;
	private Estado estado;
	private String nombrerol;
	private Date fecharegr;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	private boolean selected;

	public Rol() {
	}

	public Rol(String idrol, Estado estado, String nombrerol, Date fecharegr) {
		this.idrol = idrol;
		this.estado = estado;
		this.nombrerol = nombrerol;
		this.fecharegr = fecharegr;
	}

	public Rol(String idrol, Estado estado, String nombrerol, Date fecharegr, Set<Usuario> usuarios) {
		this.idrol = idrol;
		this.estado = estado;
		this.nombrerol = nombrerol;
		this.fecharegr = fecharegr;
		this.usuarios = usuarios;
	}

	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	public String getIdrol() {
		return this.idrol;
	}

	public void setIdrol(String idrol) {
		this.idrol = idrol;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public String getNombrerol() {
		return this.nombrerol;
	}

	public void setNombrerol(String nombrerol) {
		this.nombrerol = nombrerol;
	}

	public Date getFecharegr() {
		return this.fecharegr;
	}

	public void setFecharegr(Date fecharegr) {
		this.fecharegr = fecharegr;
	}

	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
