// default package
// Generated 02/10/2017 18:37:43 by Hibernate Tools 5.2.3.Final
package tienda.dto;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tabla generated by hbm2java
 */
@SuppressWarnings("serial")
public class Tabla implements java.io.Serializable {

	private String idtabla;
	private String nombretabla;
	private Date fechareg;
	private Set<Estado> estados = new HashSet<Estado>(0);
	private boolean selected;

	public Tabla() {
	}

	public Tabla(String idtabla, String nombretabla, Date fechareg) {
		this.idtabla = idtabla;
		this.nombretabla = nombretabla;
		this.fechareg = fechareg;
	}

	public Tabla(String idtabla, String nombretabla, Date fechareg, Set<Estado> estados) {
		this.idtabla = idtabla;
		this.nombretabla = nombretabla;
		this.fechareg = fechareg;
		this.estados = estados;
	}

	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	public String getIdtabla() {
		return this.idtabla;
	}

	public void setIdtabla(String idtabla) {
		this.idtabla = idtabla;
	}

	public String getNombretabla() {
		return this.nombretabla;
	}

	public void setNombretabla(String nombretabla) {
		this.nombretabla = nombretabla;
	}

	public Date getFechareg() {
		return this.fechareg;
	}

	public void setFechareg(Date fechareg) {
		this.fechareg = fechareg;
	}

	public Set<Estado> getEstados() {
		return this.estados;
	}

	public void setEstados(Set<Estado> estados) {
		this.estados = estados;
	}

}
